


all Makefile together here  example 




include $(TOP)/drivers/gpio/Makefile
include $(TOP)/drivers/mmc/Makefile
include $(TOP)/drivers/clk/Makefile
include $(TOP)/drivers/irq/Makefile
include $(TOP)/drivers/bus/Makefile
include $(TOP)/drivers/timer/Makefile

TOP Var will be defined at our main Makefile /os/Makefile



